#!/usr/bin/env bash

domain=$1
subdomain=$2

# Function to display information about a subdomain
display_subdomain_info() {
    local sub=$1
    local record_type=$(dig +short $sub.$domain | awk '{print $4}')
    local destination=$(dig +short $sub.$domain)
    echo "The subdomain $sub is a $record_type record and points to $destination"
}

# Check if subdomain parameter is provided
if [ -n "$subdomain" ]; then
    display_subdomain_info $subdomain
else
    # Display information for default subdomains www, lb-01, web-01, and web-02
    display_subdomain_info www
    display_subdomain_info lb-01
    display_subdomain_info web-01
    display_subdomain_info web-02
fi
