#!/usr/bin/env bash

# Install HAProxy
sudo apt-get update
sudo apt-get install -y haproxy

# Configure HAProxy
cat <<EOF | sudo tee /etc/haproxy/haproxy.cfg
global
    daemon
    maxconn 256

defaults
    mode http
    timeout connect 5000ms
    timeout client 50000ms
    timeout server 50000ms

frontend haproxy_balancer
        bind *:80
        mode http
        default_backend webservers

backend my_webservers
        balance roundrobin
        server 189607-web-01 34.207.189.161:80 check
        server 189607-web-02 100.24.235.208:80 check
EOF

# Enable HAProxy init script
sudo systemctl enable haproxy

# Restart HAProxy to apply the changes
sudo systemctl restart haproxy
