#!/usr/bin/env bash

sed -i 's/user  nginx;/user  nginx nginx;/g' /etc/nginx/nginx.conf
groupadd nginx
useradd -g nginx nginx
chown -R nginx:nginx /var/log/nginx /var/lib/nginx /var/www/html
sed -i 's/listen       80;/listen       8080;/g' /etc/nginx/conf.d/default.conf
service nginx restart
